services:
  db:
    image: postgres:15-alpine
    container_name: order-hub-db
    environment:
      POSTGRES_DB: order_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manager
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: order-hub-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/order_hub
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: manager
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
    depends_on:
      - db